wandb:
  project_name: conditional-diffusion-toy

diffusion:
  diffusion_type: vp
  timesteps: 1000
  T: 1.0 #1000.0
  eps: 1.e-5 # time epsilon for the reverse timegrid

  beta_min: 1.e-4 # 0.01
  beta_max: 0.02 # 10.0

  max_diffusivity: ~

  # diffusion_type: ve
  # timesteps: 100
  # sigma_min: 1.e-4
  # sigma_max: 0.02

data:
  data_name: toy 

# need to wire up the model arguments' with UNet class definition
model:
  name: toy-mlp #gfdm-unet #unet-diffusers # unet
  input_size: 2
  num_classes: 8
  c_in: 2 
  c_out: 2 
  time_dim: 256
  dropout_prob: 0.2 # label dropout in classifier-free training
  remove_deep_conv: false

optim:
  loss: mse
  optim_name: adamw
  weight_decay: 1.e-3
  lr: 1.e-4
  scheduler_name: onecycle
  max_lr: 1.e-2

  # for plateau:
  # min_lr: 1e-6
  # scheduler_mode: "min"
  # factor: 0.7
  # patience: 50

train:
  steps: 20000 #2000
  image_size: 1 #32
  batch_size: 256
  dataset_size: 600000
  # for toy dataset:
  label_type: index

# may need to combine this with either diffusion or validation or both
# for training don't need sampling parameters, may need to move it to the completely different evaluation config
# sampling:
#   n_steps: 100
#   guidance_scale: 0.8
#   label_to_generate: 8

validation:
  eval_freq: 10
  batch_size: 128 # maybe we want batch size of 64 for validation and then display just the first batch in wandb?
  n_steps: 100
  guidance_scale: 2.0 #0.8
  label_to_generate: 3
