wandb:
  project_name: conditional-diffusion-brain

diffusion:
  diffusion_type: vp
  T: 1.0 #1000.0 # 1.0
  eps: 1.e-3 # time epsilon for the reverse timegrid
  beta_min: 0.01 #0.1 #1.e-4 #0.01 #1.e-3 #1.e-4 # 0.01
  beta_max: 10.0 #20.0 #0.02 #10.0 #1.e-2 #0.02 # 10.0

  max_diffusivity: ~

  # diffusion_type: ve
  # timesteps: 1000
  # sigma_min: 0.01
  # sigma_max: 50
  # T: 1.0 #1000.0
  # eps: 1.e-3 # time epsilon for the reverse timegrid

# do i want to have a joint dataloader that will take care of both ANN and fmri data? 
data:
  data_name: ann-brain
  num_sessions: 40 # may need to separate it for train/test somehow 
  images_data_path: './src/diffusion_brain/data/data_coco/'
  behav_data_root: './src/diffusion_brain/data/behav/'
  subj: "subj01"
  fmri_data_root: '/data/datapool3/datasets/nsd_betas_condavg/' # TODO: add this as BIND to bash script
  fmri_data_name: 'betas_average_fsaverage.npy'
  ann_model: "resnet50" 
  ann_model_weights: "ResNet50_Weights.IMAGENET1K_V2"
  ann_activations_data_path: './src/diffusion_brain/data/ann_activations/'
  layer_name: "avgpool"
  ann_input_size: 256
  roi: 1 # do the correct indexing as described in roi_defs/streams.mgz.ctab
  roi_defs_dir: './src/diffusion_brain/data/roi_defs/'
  roi_file: "streams" # can be HCP_MMP1 or nsdgeneral

# need to wire up the model arguments' with UNet class definition
model:
  name: unet-diffusers #gfdm-unet #unet-diffusers # unet
  input_size: 32
  num_classes: 10
  c_in: 1
  c_out: 1
  time_dim: 256
  cross_attention_dim: 128
  dropout_prob: 0.2 # label dropout in classifier-free training
  remove_deep_conv: false
  save_freq: 500
  output_folder: './model_outputs/ann-brain/'

optim:
  loss: mse
  optim_name: adamw
  weight_decay: 1.e-3
  lr: 1.e-4 # for adam/optimiser
  scheduler_name: onecycle
  max_lr: 1.e-4

  # for plateau:
  # min_lr: 1e-6
  # scheduler_mode: "min"
  # factor: 0.7
  # patience: 50

train:
  steps: 1000 #2000
  image_size: 32
  batch_size: 32
  dataset_size: 9485 # 10000 - 515 images as train
  num_workers: 4

# may need to combine this with either diffusion or validation or both
# for training don't need sampling parameters, may need to move it to the completely different evaluation config
# sampling:
#   n_steps: 100
#   guidance_scale: 0.8
#   label_to_generate: 8

validation:
  eval_freq: 100
  batch_size: 32 # maybe we want batch size of 64 for validation and then display just the first batch in wandb?
  n_steps: 1000
  guidance_scale: 0.0 #0.8
  label_to_generate: 5
  output_folder: './outputs/ann-brain/'
  num_workers: 1
